sudo: false
language: node_js
node_js:
  - stable
addons:
  firefox: latest
env:
  global:
    - DISPLAY=:99.0
    - JPM_FIREFOX_BINARY=/usr/local/bin/firefox
before_install:
  - gem install sass
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g jpm
script:
  - ./make.sh --debug
  - (! grep -E "^(TEST-INFO \| \[JavaScript Error)" testlog.txt)